version: "3.9"
services:
  scanner:
    build: .
    platform: linux/amd64
    volumes:
      - ./:/app
      # Required for executing commands in other docker containers
      - "/var/run/docker.sock:/var/run/docker.sock"
    # Required for reaching other docker containers
    networks:
      - challenge_default

# Required for reaching other docker containers
networks:
  challenge_default:
    external: true
